### ISSUE TITLE
Push Github

### ISSUE THREAD

**Issue by sebastiendardenne** [quillaur/data_learning#9]
Bonjour,
J'ai pu cloner le repo GitHub et créer localement ma branche et mettre mes solutions.

Par contre, quand je fais un
git push origin temperatureSD (temperatureSD est ma branche)
j'ai une erreur d'authentification...

pareil pour  git push https://github.com/quillaur/studi_algo_python.git/ temperatureSD

En fait, il me demande un login/passwd et je pense que git s'attend au credentiel de Aurélien, pas les miens.

Pourrais tu me dire ou je me trompe? 

Merci par avance

Sébastien

**Comment by sebastiendardenne** [comment]
> Bonjour, J'ai pu cloner le repo GitHub et créer localement ma branche et mettre mes solutions.
> 
> Par contre, quand je fais un git push origin temperatureSD (temperatureSD est ma branche) j'ai une erreur d'authentification...
> 
> pareil pour git push https://github.com/quillaur/studi_algo_python.git/ temperatureSD
> 
> En fait, il me demande un login/passwd et je pense que git s'attend au credentiel de Aurélien, pas les miens.
> 
> Pourrais tu me dire ou je me trompe?
> 
> Merci par avance
> 
> Sébastien

**Comment by sebastiendardenne** [comment]
Bonjour,

Il semble que je doive suivre le process suivant :
1. créer fork du projet  - le projet se retrouve sur mon GitHub
2. s'aiguiller sur le bon commit - git add fichier / git commit-m "message" / git push
3. Revenir sur l'interface web et faire un pull request

Dites moi si vous voyez les fichiers uploadés/proposés

Merci

SD

**Comment by quillaur** [comment]
En effet, ce que tu proposes est correct. Je ne savais pas que c'était une obligation sur github public de passer par un fork pour pouvoir bosser sur le projet. Désolé pour ce contretemps...

**Comment by quillaur** [comment]
Désolé, je pense avoir perdu l'une de tes solutions en réarrangeant l'architecture du projet. N'hésite pas à regarder la branche main et me dire s'il manque quelque chose pour que je le rajoute.

Merci.

**Comment by sebastiendardenne** [comment]
Je vais regarder. Pas de problèmes. 

Merci
